### ISSUE TITLE
graph classification in demos - unable to load any stellargraph package

### ISSUE THREAD

**Issue by takingstock** [stellargraph/stellargraph#1171]
### Describe the bug
I simply cloned the repository and tried running the notebook for graph classification and keep getting these errors
ImportError: cannot import name 'GraphGenerator'
ImportError: cannot import name 'GCNSupervisedGraphClassification'

### To Reproduce

Run notebook 
supervised-graph-classification.ipynb

### Observed behavior
Traceback (most recent call last):
  File "supervised-graph-classification.py", line 38, in <module>
    from stellargraph.mapper import GraphGenerator

### Expected behavior
Normal run ?

### Environment

Operating system: *Ubuntu*

Python version: *fPython 3.6.7*

Package versions: *stellargraph==0.10.0, tensorflow=='1.14.0'*

Operating system: `Linux-4.4.0-1104-aws-x86_64-with-debian-stretch-sid`
Python version:
```
3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42)
[GCC 7.3.0]
```
Package versions:
<details>

```
absl-py==0.9.0
alabaster==0.7.10
anaconda-client==1.6.14
anaconda-project==0.8.2
asn1crypto==0.24.0
astor==0.8.0
astroid==1.6.3
attrs==18.1.0
Automat==0.3.0
autovizwidget==0.13.1
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
bcrypt==3.1.7
beautifulsoup4==4.6.0
bert-embedding==1.0.1
bert-serving-client==1.10.0
bert-serving-server==1.10.0
bitarray==0.8.1
bleach==2.1.3
boto==2.48.0
boto3==1.10.24
botocore==1.13.24
bz2file==0.98
cached-property==1.5.1
certifi==2019.11.28
cffi==1.11.5
characteristic==14.3.0
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
clyent==1.2.2
colorama==0.3.9
contextlib2==0.5.5
cryptography==2.8
cycler==0.10.0
Cython==0.28.4
cytoolz==0.9.0.1
dask==1.2.2
decorator==4.3.0
defusedxml==0.6.0
distributed==1.28.1
docker==4.1.0
docker-compose==1.25.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
entrypoints==0.2.3
environment-kernels==1.1.1
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
gast==0.3.3
gensim==3.8.0
gevent==1.3.0
glob2==0.6
gluonnlp==0.6.0
gmpy2==2.0.8
google-pasta==0.2.0
GPUtil==1.4.0
graphviz==0.8.4
greenlet==0.4.13
grpcio==1.27.2
h5py==2.10.0
hdijupyterutils==0.13.1
heapdict==1.0.0
horovod==0.18.2
html5lib==1.0.1
idna==2.6
imageio==2.6.1
imagesize==1.0.0
imutils==0.5.3
ipykernel==4.8.2
ipyparallel==6.2.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.4.0
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
jmespath==0.9.4
joblib==0.14.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
Keras==2.2.4
Keras-Applications==1.0.8
keras-bert==0.80.0
keras-embed-sim==0.7.0
keras-layer-normalization==0.14.0
keras-multi-head==0.22.0
keras-pos-embd==0.11.0
keras-position-wise-feed-forward==0.6.0
Keras-Preprocessing==1.1.0
keras-radam==0.15.0
keras-self-attention==0.41.0
keras-transformer==0.31.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.23.1
locket==0.2.0
lxml==4.2.1
Markdown==3.1.1
MarkupSafe==1.0
matplotlib==3.1.3
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.0
mkl-service==2.3.0
mock==3.0.5
more-itertools==4.1.0
mpmath==1.0.0
msgpack==0.6.0
msgpack-python==0.5.6
multipledispatch==0.5.0
mxnet==1.4.0
nb-conda==2.2.1
nb-conda-kernels==2.2.2
nbconvert==5.4.1
nbformat==4.4.0
networkx==2.3
nltk==3.3
nose==1.3.7
notebook==5.5.0
num2words==0.5.10
numpy==1.15.4
numpydoc==0.8.0
olefile==0.45.1
openpyxl==2.5.3
opt-einsum==3.1.0
packaging==17.1
pandas==0.25.3
pandocfilters==1.4.2
paramiko==2.6.0
parso==0.2.0
partd==0.3.8
path.py==11.0.1
pathlib2==2.3.2
pep8==1.7.1
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.2.0
pkginfo==1.4.2
plotly==4.3.0
pluggy==0.6.0
ply==3.11
prompt-toolkit==1.0.15
protobuf==3.8.0
protobuf3-to-dict==0.1.5
psutil==5.4.5
psycopg2==2.7.5
ptyprocess==0.5.2
py==1.5.3
py4j==0.10.7
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.4
pyflakes==1.6.0
pygal==2.4.0
Pygments==2.2.0
pykerberos==1.2.1
pylint==1.8.4
PyNaCl==1.3.0
pyodbc==4.0.23
pyOpenSSL==18.0.0
pyparsing==2.2.0
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtWebEngine==5.12.1
PySocks==1.6.8
pyspark==2.3.2
pytest==3.5.1
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
python-Levenshtein==0.12.0
pytz==2018.4
PyWavelets==1.1.1
PyYAML==3.12
pyzbar==0.1.8
pyzmq==19.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
regex==2020.2.20
requests==2.20.0
requests-kerberos==0.12.0
retrying==1.3.3
rope==0.10.7
ruamel-yaml==0.15.35
s3fs==0.1.5
s3transfer==0.2.1
sagemaker==1.44.0
sagemaker-pyspark==1.2.6
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
smart-open==1.9.0
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
sparkmagic==0.12.5
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.2.11
stellargraph==0.10.0
sympy==1.1.1
TBB==0.1
tblib==1.3.2
tensorboard==1.15.0
tensorflow==1.14.0
tensorflow-estimator==1.15.1
tensorflow-gpu==1.15.0
tensorflow-serving-api==1.15.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
texttable==1.6.2
toolz==0.9.0
tornado==5.0.2
tqdm==4.43.0
traitlets==4.3.2
typing==3.6.6
unicodecsv==0.14.1
UNKNOWN==0.0.0
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
Werkzeug==0.14.1
widgetsnbextension==3.4.2
words2num==0.2.3
wrapt==1.12.1
xlrd==1.1.0
XlsxWriter==1.0.4
xlwt==1.3.0
xmltodict==0.12.0
zict==0.1.3

```

</details>

### Additional context

Add any other context about the problem here. For example:

Data used: *if this occurs with a specific dataset, which dataset and how to acquire it*

Screenshots: *if applicable, add some screenshots to explain the behaviour*

**Comment by huonw** [comment]
Hi, thanks for trying StellarGraph and providing so much information about the problem. The dedicated graph classification algorithm is only available in StellarGraph version 0.11, but it looks like you've got stellargraph 0.10. If you installed via Conda, unfortunately our Conda packages are broken at the moment (#1166 and #1165), and we only discovered it as we were doing the 0.11 release.

One way to solve this would be to install via pip, such as `pip install stellargraph==0.11.0` or `pip install .` in the repository code you cloned. Please let us know if that helps, while we're working on fixing the conda packages.

**Comment by timpitman** [comment]
Hi @takingstock, thanks again for letting us know about this problem.We've just released a new [version 0.11.1](https://github.com/stellargraph/stellargraph/releases/tag/v0.11.1) which should resolve your issue with an updated Conda package.  You should now be able to re-install StellarGraph using [Conda}(https://anaconda.org/stellargraph/stellargraph).  Please let us know if the new version resolves your issue.

**Comment by takingstock** [comment]
thanks for taking the time out .. still no luck ..
i did install sg using conda as instructed BUT as per your docs, for both pip and install via github, i see that installing demos separately is required .. but in the conda section this instruction is absent and i couldn't figure out how to do the same via conda .. kindly take a look

pasting some logs below

(tensorflow_p36) ubuntu@ip-172-31-16-151:~/VISION_EXP/VISION_EXP/graph_conv/stellargraph$ conda install -c stellargraph stellargraph
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/ubuntu/anaconda3/envs/tensorflow_p36

  added / updated specs:
    - stellargraph


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    smart_open-1.9.0           |             py_0          59 KB
    stellargraph-0.8.3         |             py_0        21.9 MB  stellargraph
    bz2file-0.98               |           py36_1          13 KB
    gensim-3.8.0               |   py36h962f231_0        22.9 MB
    networkx-2.3               |             py_0         1.1 MB
    ------------------------------------------------------------
                                           Total:        46.0 MB

The following NEW packages will be INSTALLED:

    bz2file:      0.98-py36_1
    gensim:       3.8.0-py36h962f231_0
    smart_open:   1.9.0-py_0
    stellargraph: 0.8.3-py_0           stellargraph

The following packages will be UPDATED:

    networkx:     2.1-py36_0                        --> 2.3-py_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
smart_open-1.9.0     | 59 KB     | ################################################################################################################################################## | 100%
stellargraph-0.8.3   | 21.9 MB   | ################################################################################################################################################## | 100%
bz2file-0.98         | 13 KB     | ################################################################################################################################################## | 100%
gensim-3.8.0         | 22.9 MB   | ################################################################################################################################################## | 100%
networkx-2.3         | 1.1 MB    | ################################################################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(tensorflow_p36) ubuntu@ip-172-31-16-151:~/VISION_EXP/VISION_EXP/graph_conv/stellargraph/demos/graph-classification$ python supervised-graph-classification.py
Traceback (most recent call last):
  File "supervised-graph-classification.py", line 38, in <module>
    from stellargraph.mapper import GraphGenerator
ImportError: cannot import name 'GraphGenerator'

**Comment by timpitman** [comment]
Hi @takingstock, thanks for providing extra information with the logs.  Feedback on these issues is very valuable, and we do have additional work planned, including #1172 to check the StellarGraph version match when running notebooks, and I've added #1202 to improve our instructions for running demos.

It looks as though you installed an older 0.8.3 version of StellarGraph, which isn't compatible with the most recent demo notebooks.

The logs you supplied do warn about an old version of Conda - could you please update that as suggested with the following command?:
```
conda update -n base -c defaults conda
```

Following that, Conda should install the most recent version of StellarGraph, but to make sure, it's possible to specify a specific version to install:
```
 conda install -c stellargraph stellargraph=0.11.1
```

**Comment by timpitman** [comment]
Hi @takingstock, just following up so that we can (hopefully) close this issue - did updating Conda and StellarGraph resolve your problem?
